"""sentinel.publish: what gets published, how the PR text is escaped, and the git steps (faked)."""

from __future__ import annotations

import subprocess
from pathlib import Path

import pytest

from sentinel import publish as pub

RULE = "title: t\ndetection:\n  selection:\n    Image|endswith: \\cmd.exe\n  condition: selection"


def _row(**kw) -> dict:
    return {
        "alert_id": "day3-070",
        "outcome": "rule_passed",
        "verdict": "true_positive",
        "triage_techniques": ["T1059.003"],
        "rulegen": {"title": "User-folder EXE spawning cmd"},
        "rule_yaml": RULE,
        "validation": {"true_positives": 4, "false_positives": 0, "feedback": "TP: 4/4"},
        "recall": 1.0,
        "attempt_passes": [False, True],
        "best_attempt": 2,
    } | kw


@pytest.mark.parametrize(
    "row",
    [
        _row(outcome="rule_failed"),
        _row(outcome="benign"),
        _row(rule_yaml=""),
        _row(alert_id="../../etc"),
        _row(alert_id="a b"),
    ],
)
def test_only_passed_or_review_rules_with_a_safe_id_are_published(row):
    with pytest.raises(pub.PublishError):
        pub.build_plan(row)


def test_plan_for_a_passed_rule():
    plan = pub.build_plan(_row())
    assert plan.branch == "rule/day3-070"
    assert plan.path.as_posix() == "rules/generated/day3-070.yml"
    assert plan.title == "Rule for day3-070: User-folder EXE spawning cmd"
    assert "| held-out repeats caught | 4 (recall 1.00) |" in plan.body
    assert "| version shipped | 2 of 2 |" in plan.body
    assert "```yaml\n" + RULE in plan.body
    assert plan.rule_text.startswith("# Generated by Sentinel Loop") and RULE in plan.rule_text


def test_needs_review_is_marked_in_title_and_body():
    plan = pub.build_plan(_row(outcome="rule_needs_review"))
    assert plan.title.startswith("[needs review] ")
    assert "Needs human review" in plan.body


def test_model_text_cannot_break_the_pr_markdown():
    evil_title = "x\n## Approved by security | `merge me`"
    evil_rule = RULE + "\n# ```\n# [click](http://evil)"
    plan = pub.build_plan(_row(rulegen={"title": evil_title}, rule_yaml=evil_rule))
    assert "\n" not in plan.title and "`" not in plan.title and "|" not in plan.title
    assert "````yaml\n" in plan.body  # fence longer than the ``` inside the rule


def test_dry_run_runs_nothing(tmp_path):
    def boom(*a, **k):
        raise AssertionError("dry run must not run commands")

    cmds = pub.publish(pub.build_plan(_row()), run=boom, worktree=tmp_path / "wt")
    assert ["git", "push", "origin", "main"] not in cmds
    assert any(c[:4] == ["gh", "pr", "create", "--draft"] for c in cmds)


class FakeGit:
    """Records commands; 'git worktree add' creates the folder, like git would."""

    def __init__(self, worktree: Path, fail_on: str | None = None):
        self.worktree, self.fail_on, self.calls = worktree, fail_on, []

    def __call__(self, cmd, check=False, cwd=None):
        self.calls.append(cmd)
        if cmd[:3] == ["git", "worktree", "add"]:
            self.worktree.mkdir(parents=True)
        if cmd[:3] == ["git", "worktree", "remove"]:
            import shutil

            shutil.rmtree(self.worktree)
        if cmd[:3] == ["git", "-C", str(self.worktree)] and cmd[3] == "add":
            assert (self.worktree / "rules/generated/day3-070.yml").exists()
        if self.fail_on and self.fail_on in cmd:
            raise subprocess.CalledProcessError(1, cmd)
        return subprocess.CompletedProcess(cmd, 0)


def test_open_writes_the_rule_in_a_worktree_and_cleans_up(tmp_path):
    wt = tmp_path / "wt"
    git = FakeGit(wt)
    pub.publish(pub.build_plan(_row()), dry_run=False, run=git, worktree=wt)
    assert git.calls[1][:5] == ["git", "worktree", "add", "-b", "rule/day3-070"]
    assert ["git", "-C", str(wt), "push", "-u", "origin", "rule/day3-070"] in git.calls
    assert git.calls[-1][:3] == ["git", "worktree", "remove"]
    assert not wt.exists() and not list(tmp_path.glob("publish-*.md"))


def test_a_failed_push_still_cleans_up(tmp_path):
    wt = tmp_path / "wt"
    git = FakeGit(wt, fail_on="push")
    with pytest.raises(subprocess.CalledProcessError):
        pub.publish(pub.build_plan(_row()), dry_run=False, run=git, worktree=wt)
    assert not any(c[0] == "gh" for c in git.calls)  # no PR without a pushed branch
    assert not wt.exists()


def test_leftover_worktree_is_refused(tmp_path):
    wt = tmp_path / "wt"
    wt.mkdir()
    with pytest.raises(pub.PublishError, match="did not clean up"):
        pub.publish(pub.build_plan(_row()), dry_run=False, run=FakeGit(wt), worktree=wt)
