"""The rule gate (evals/validate_rules.py) on real golden data: the CI step that blocks bad rules.

Rules are real rule_gen outputs: day3-070 v0 (results/rulegen-v0.json, passes 4/4 under pass
bar v2) and day3-056's broad MSBuild rule (results/rulegen-try.json, fires on a benign event).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from evals import validate_rules
from evals.triage_smoke import load_golden

GOOD_RULE = """\
# Generated by Sentinel Loop from alert day3-070 (rule_passed).
title: Suspicious Desktop Executable Spawning Cmd to Execute Another Desktop Binary
id: aa359567-e160-5c86-ae1d-f3a7a83275e0
status: experimental
tags:
- attack.t1059.003
- attack.t1204.002
logsource:
  category: process_creation
  product: windows
detection:
  selection1:
    ParentImage|contains:
    - Desktop
    Image|endswith:
    - cmd.exe
    CommandLine|contains:
    - /c
    - Desktop
    - .exe
  condition: 1 of selection*
level: high
"""

BROAD_RULE = """\
title: MSBuild Execution with Project File from Suspicious Directory
id: 6c81e1a5-63ae-56c2-870c-6bbf5a4a073f
tags:
- attack.t1127.001
logsource:
  category: process_creation
  product: windows
detection:
  selection1:
    Image|endswith:
    - MSBuild.exe
    CommandLine|contains:
    - .xml
    - Windows/Tasks/
  condition: 1 of selection*
"""


@pytest.fixture(scope="module")
def alerts():
    return load_golden()[1]


def write(tmp_path: Path, name: str, text: str) -> Path:
    path = tmp_path / f"{name}.yml"
    path.write_text(text, encoding="utf-8")
    return path


def test_good_rule_passes(tmp_path, alerts):
    r = validate_rules.check(write(tmp_path, "day3-070", GOOD_RULE), alerts)
    assert r.verdict == "passed"
    assert r.reasons == []


def test_broad_rule_is_blocked(tmp_path, alerts):
    r = validate_rules.check(write(tmp_path, "day3-056", BROAD_RULE), alerts)
    assert r.verdict == "failed"
    assert any("benign" in x for x in r.reasons)
    assert any("dead values" in x for x in r.reasons)  # 'Windows/Tasks/' never matches


def test_filter_on_process_name_is_blocked(tmp_path, alerts):
    """RG-3: excluding by Image lets an attacker hide by running from that name."""
    rule = GOOD_RULE.replace(
        "  condition: 1 of selection*",
        "  filter1:\n    Image|endswith:\n    - svchost.exe\n"
        "  condition: 1 of selection* and not 1 of filter*",
    )
    r = validate_rules.check(write(tmp_path, "day3-070", rule), alerts)
    assert r.verdict == "failed"
    assert any("RG-3" in x for x in r.reasons)


def test_broken_yaml_is_blocked(tmp_path, alerts):
    r = validate_rules.check(write(tmp_path, "day3-070", "title: [unclosed\n"), alerts)
    assert r.verdict == "failed"
    assert any("compile" in x for x in r.reasons)


def test_unknown_alert_is_blocked(tmp_path, alerts):
    r = validate_rules.check(write(tmp_path, "not-an-alert", GOOD_RULE), alerts)
    assert r.verdict == "failed"
    assert "golden set" in r.reasons[0]


def test_rule_without_technique_is_blocked(tmp_path, alerts):
    rule = GOOD_RULE.replace("- attack.t1059.003\n- attack.t1204.002\n", "- attack.execution\n")
    r = validate_rules.check(write(tmp_path, "day3-070", rule), alerts)
    assert r.verdict == "failed"
    assert "technique" in r.reasons[0]


def test_techniques_from_tags():
    assert validate_rules.techniques(GOOD_RULE) == ["T1059.003", "T1204.002"]
    assert validate_rules.techniques("tags: [attack.execution, attack.T1218]") == ["T1218"]
    assert validate_rules.techniques("title: [unclosed") == []


def test_exit_codes(tmp_path, monkeypatch, capsys):
    monkeypatch.setattr(validate_rules, "RULES_DIR", tmp_path / "rules" / "generated")
    assert validate_rules.main([]) == 0  # no folder yet: nothing to check
    good = write(tmp_path, "day3-070", GOOD_RULE)
    broad = write(tmp_path, "day3-056", BROAD_RULE)
    assert validate_rules.main([str(good)]) == 0
    assert validate_rules.main([str(good), str(broad)]) == 1
    assert "1/2 rules pass" in capsys.readouterr().out
