"""Open a generated rule as a draft pull request (Week 3, Day 17).

    uv run python -m sentinel.publish --results results/repair-try2.json --alert day3-070
    uv run python -m sentinel.publish --results ... --alert ... --open    # really push + open

Only rules with outcome rule_passed or rule_needs_review are published. The rule goes to
`rules/generated/<alert-id>.yml` on a new branch `rule/<alert-id>` cut from origin/main, and a
DRAFT PR is opened with the triage verdict and the validator report. A human reviews and merges;
CI re-validates the rule (Mouadh's validate_rules job). Nothing is ever pushed to main.

Dry run is the default: it prints the branch, file, PR title and body and the commands, and runs
nothing. With --open the git work happens in a throwaway worktree (data/raw/publish-wt), so the
branch you are on and your uncommitted changes are never touched. The commit is authored by the
git identity of whoever runs it: the person who approves publishing.

The rule and its title were written by a model from attacker-controlled logs: the title is cut to
one plain line, and the YAML and the validator report go into code fences longer than any
backtick run inside them, so log text can't break out into the PR's markdown.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RULES_DIR = Path("rules") / "generated"
WORKTREE = ROOT / "data" / "raw" / "publish-wt"  # gitignored
PUBLISHABLE = {"rule_passed", "rule_needs_review"}
SAFE_ID = re.compile(r"[A-Za-z0-9._-]{1,64}")

Runner = Callable[..., subprocess.CompletedProcess]


class PublishError(RuntimeError):
    pass


@dataclass(frozen=True)
class PublishPlan:
    alert_id: str
    outcome: str
    branch: str
    path: Path  # relative to the repo root
    title: str
    body: str
    rule_text: str


def build_plan(row: dict) -> PublishPlan:
    """A rule-gen results row (evals/rulegen.py) -> what to publish. Raises PublishError when the
    row has nothing publishable."""
    alert_id = str(row.get("alert_id", ""))
    if not SAFE_ID.fullmatch(alert_id):
        raise PublishError(f"unsafe or missing alert id: {alert_id!r}")
    outcome = row.get("outcome")
    if outcome not in PUBLISHABLE:
        raise PublishError(f"{alert_id}: outcome {outcome!r} is not publishable ({PUBLISHABLE})")
    rule = (row.get("rule_yaml") or "").strip()
    if not rule:
        raise PublishError(f"{alert_id}: no rule")

    review = outcome == "rule_needs_review"
    rule_title = _one_line((row.get("rulegen") or {}).get("title") or "generated rule", 80)
    title = ("[needs review] " if review else "") + f"Rule for {alert_id}: {rule_title}"
    header = (
        f"# Generated by Sentinel Loop from alert {alert_id} ({outcome}).\n"
        "# Model-written: review before merging. Validator report in the pull request.\n"
    )
    return PublishPlan(
        alert_id=alert_id,
        outcome=outcome,
        branch=f"rule/{alert_id}",
        path=RULES_DIR / f"{alert_id}.yml",
        title=title,
        body=_body(row, rule, review),
        rule_text=header + rule + "\n",
    )


def _body(row: dict, rule: str, review: bool) -> str:
    v = row.get("validation") or {}
    recall = row.get("recall")
    attempts = len(row.get("attempt_passes") or []) or 1
    techniques = ", ".join(row.get("triage_techniques") or []) or "-"
    lines = [
        "Draft opened by `sentinel.publish`. **The rule was written by a model from attacker-"
        "controlled logs: read it before merging.** CI re-validates it.",
        "",
        "| | |",
        "|---|---|",
        f"| alert | `{row['alert_id']}` |",
        f"| triage | {_one_line(str(row.get('verdict')), 30)}, "
        f"techniques {_one_line(techniques, 80)} |",
        f"| outcome | `{row.get('outcome')}` |",
        f"| held-out repeats caught | {v.get('true_positives', '-')}"
        + (f" (recall {recall:.2f})" if isinstance(recall, float) else "")
        + " |",
        f"| benign hits | {v.get('false_positives', '-')} |",
        f"| version shipped | {row.get('best_attempt') or attempts} of {attempts} |",
        "",
    ]
    if review:
        lines += [
            "**Needs human review:** 0 benign hits, but the golden set has no other example of "
            "this attack to test the rule on. Decide from the rule itself.",
            "",
        ]
    lines += [
        "### Rule",
        _fenced(rule, "yaml"),
        "",
        "### Validator report",
        _fenced(v.get("feedback") or "(none)", "text"),
    ]
    return "\n".join(lines) + "\n"


def _one_line(text: str, limit: int) -> str:
    """Plain single line for titles and table cells: no newlines, pipes or backticks."""
    flat = re.sub(r"[\r\n|`]+", " ", text).strip()
    return flat[:limit]


def _fenced(text: str, lang: str) -> str:
    longest = max((len(m) for m in re.findall(r"`+", text)), default=0)
    fence = "`" * max(3, longest + 1)
    return f"{fence}{lang}\n{text.rstrip()}\n{fence}"


def commands(plan: PublishPlan, body_file: Path, worktree: Path = WORKTREE) -> list[list[str]]:
    wt = str(worktree)
    return [
        ["git", "fetch", "origin", "main"],
        ["git", "worktree", "add", "-b", plan.branch, wt, "origin/main"],
        # (the rule file is written into the worktree here)
        ["git", "-C", wt, "add", plan.path.as_posix()],
        ["git", "-C", wt, "commit", "-m", f"Generated rule for {plan.alert_id} ({plan.outcome})"],
        ["git", "-C", wt, "push", "-u", "origin", plan.branch],
        [
            "gh", "pr", "create", "--draft", "--base", "main", "--head", plan.branch,
            "--title", plan.title, "--body-file", str(body_file),
        ],
    ]  # fmt: skip


def publish(
    plan: PublishPlan,
    *,
    dry_run: bool = True,
    run: Runner = subprocess.run,
    worktree: Path = WORKTREE,
) -> list[list[str]]:
    """Returns the commands (run, or only planned when dry_run). Always removes the worktree."""
    body_file = worktree.parent / f"publish-{plan.alert_id}.md"
    cmds = commands(plan, body_file, worktree)
    if dry_run:
        return cmds
    if worktree.exists():
        raise PublishError(f"{worktree} exists: a previous publish did not clean up, remove it")
    body_file.parent.mkdir(parents=True, exist_ok=True)
    body_file.write_text(plan.body, encoding="utf-8")
    try:
        for i, cmd in enumerate(cmds):
            run(cmd, check=True, cwd=ROOT)
            if i == 1:  # worktree created: write the rule into it
                target = worktree / plan.path
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(plan.rule_text, encoding="utf-8")
    finally:
        if worktree.exists():
            run(["git", "worktree", "remove", "--force", str(worktree)], check=False, cwd=ROOT)
        body_file.unlink(missing_ok=True)
    return cmds


def main(argv: Sequence[str] | None = None) -> None:
    p = argparse.ArgumentParser(prog="python -m sentinel.publish")
    p.add_argument("--results", required=True, type=Path, help="evals.rulegen results JSON")
    p.add_argument("--alert", required=True, help="alert id of the row to publish")
    p.add_argument("--open", action="store_true", help="really push and open the draft PR")
    args = p.parse_args(argv)

    rows = json.loads(args.results.read_text(encoding="utf-8"))["rows"]
    row = next((r for r in rows if r.get("alert_id") == args.alert), None)
    if row is None:
        raise SystemExit(f"{args.alert} not in {args.results}")
    try:
        plan = build_plan(row)
    except PublishError as e:
        raise SystemExit(f"not published: {e}") from e
    if args.open and not shutil.which("gh"):
        raise SystemExit("gh (GitHub CLI) not found: install it and run `gh auth login`")

    print(f"branch: {plan.branch}\nfile:   {plan.path.as_posix()}\ntitle:  {plan.title}\n")
    print(plan.body.encode("ascii", "replace").decode())
    cmds = publish(plan, dry_run=not args.open)
    print("ran:" if args.open else "dry run, would run (add --open to do it):")
    for c in cmds:
        print("  " + subprocess.list2cmdline(c))


if __name__ == "__main__":
    main()
